### PR TITLE
Multiple small fixes

### PR DESCRIPTION
**Pull request by charludo**
### Short description

Multiple small last-minute fixes

### Proposed changes

- fix: links to wards/rooms in patient list now work again (and open the corresponding room automatically)
- change: sort patient list by update instead of creation, just be a bit more convenient
- change: mayyyybe sped up patient list a little (not sure haha)
- fix: button layout in assignment view was broken on desktop
- fix: bed assignment form was not being translated into German
- change: reword help text for `discharge_date` into "Estimated discharge date" by recommendation of a medical professional in my family. This only really affects the intake form. 
- fix: text alignment in "suggest assignment" button in ward view
- fix: show `-` instead of `None ()` in patient card of patient has no diagnosis

### Side effects

- 
- 

### Resolved issues

Fixes: n/a

### CODE REVIEW

**Review by noworneverev — COMMENTED** [review]
No questions to above, but I have a small question regarding the test data, some patients are born in the future and the age will display "-1". This is not related to final presentation data though, are we going to load only data_final_presentation?

**Comment by charludo** [comment]
> No questions to above, but I have a small question regarding the test data, some patients are born in the future and the age will display "-1". This is not related to final presentation data though, are we going to load only data_final_presentation?

Wait, so the midterm data contains patients that are not yet born?

In any case, good catch, I will limit the age to 0

**Comment by charludo** [comment]
> > No questions to above, but I have a small question regarding the test data, some patients are born in the future and the age will display "-1". This is not related to final presentation data though, are we going to load only data_final_presentation?
> 
> Wait, so the midterm data contains patients that are not yet born?
> 
> In any case, good catch, I will limit the age to 0

done

**Comment by noworneverev** [comment]
> > No questions to above, but I have a small question regarding the test data, some patients are born in the future and the age will display "-1". This is not related to final presentation data though, are we going to load only data_final_presentation?
> 
> Wait, so the midterm data contains patients that are not yet born?
> 
> In any case, good catch, I will limit the age to 0

Yeah, like this one:
```
  {
    "model": "cms.patient",
    "pk": 175,
    "fields": {
      "creator": 4,
      "created_at": "2024-01-20T13:47:00Z",
      "updated_at": "2024-01-14T07:24:50.995Z",
      "insurance_type": false,
      "first_name": "Sanjiva",
      "last_name": "Kownatzki",
      "gender": "m",
      "date_of_birth": "2024-03-22",
      "_first": "4f6b-836e-1d8d59c525fd",
      "_last": "73ecd750-73e0"
    }
  },
```

**Review by noworneverev — APPROVED** [review]

**Pull request merged**
