### PR TITLE
Assignment suggestions using Tabea's PRA solver

### LINKED ISSUE #20: Add possibility to hook into a given bed management heuristic
### Motivation

Station managers need a way to let an algorithm suggest a bed assignment

### PR DESCRIPTION
**Pull request by charludo**
### Short description

The "suggest assignment" button finally works! 🥳 🎉 

### Proposed changes

- add management command for exporting ward patients to Tabea's format, using her solver, and returning the solution
- clicking the "suggest assignment" button takes you to the normal timeline view, with the option to save, cancel, or edit the timeline as usual

### Please Note

- #93 should be merged BEFORE this, so if you want to review this PR, please instead review that one 😉 
- the bed assignments aren't exactly ideal, but this is not on us. Not sure if there is an error in the solver, or if it is just due to the rounding. We will have to wait and see how it works with the final presentation data; before then, there isn't really anything we can do with this.
- this does not work for Pädiatrie, because the solver cannot handle rooms with more than 2 beds (see error in console)

### Installation
- clone [TabeaBrandt/patient-to-room_assignment](https://github.com/TabeaBrandt/patient-to-room_assignment/) next to where your copy of `ycms` lives
- inside `patient-to-room_assignment`, do
    - `python -m venv .venv`
    - `. .venv/bin/activate`
    - `pip install gurobipy` 

### Resolved issues

Fixes: #20

### CODE REVIEW

**Comment by SnehaR26** [comment]
A doubt:
I am on the branch automatic-assignment
So I installed patient-to-room_assignment in the same directory as ycms. I installed gurobi in the same virtual environment as rest of the project (its called denv). I run ycms and click on suggest assignment but nothing seems to pop up, What am i missing?

**Comment by charludo** [comment]
> A doubt:
> I am on the branch automatic-assignment
> So I installed patient-to-room_assignment in the same directory as ycms. I installed gurobi in the same virtual environment as rest of the project (its called denv). I run ycms and click on suggest assignment but nothing seems to pop up, What am i missing?

Please follow the instructions as given:

- clone [TabeaBrandt/patient-to-room_assignment](https://github.com/TabeaBrandt/patient-to-room_assignment/) next to where your copy of `ycms` lives
- inside `patient-to-room_assignment`, do
    - `python -m venv .venv`
    - `. .venv/bin/activate`
    - `pip install gurobipy` 

"next to" means that the two are "siblings".
For example,
```
/home/sneha/ycms/
/home/sneha/patient-to-room_assignment
```
but not
```
/home/sneha/ycms/
/home/sneha/ycms/patient-to-room_assignment
```

> (its called denv)

I am really not sure how that works, the `install.sh` script handles virtual environments in our project, and it will always be located in `.venv`.

In any case, you need a separate one, as the instructions say.

**Comment by SnehaR26** [comment]
> 
> "next to" means that the two are "siblings". For example,
> 
> ```
> /home/sneha/ycms/
> /home/sneha/patient-to-room_assignment
> ```
>
> but not
> 
> ```
> /home/sneha/ycms/
> /home/sneha/ycms/patient-to-room_assignment
> ```
Yup they are siblings.
> > (its called denv)
> 
> I am really not sure how that works, the `install.sh` script handles virtual environments in our project, and it will always be located in `.venv`.
> 
> In any case, you need a separate one, as the instructions say.

I had created a virtual env denv in the begining where I installed everything in ycms. I followed the instructions also and added venv inside patient-to-room directory. and then I went back to ycms and ran it. clicking on suggest assignment didn't do anything for me. Am I supposed to directly click on that or I check in timetravel for assignments and then it will show

**Comment by charludo** [comment]
> > "next to" means that the two are "siblings". For example,
> > ```
> > /home/sneha/ycms/
> > /home/sneha/patient-to-room_assignment
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but not
> > ```
> > /home/sneha/ycms/
> > /home/sneha/ycms/patient-to-room_assignment
> > ```
> 
> Yup they are siblings.
> 
> > > (its called denv)
> > 
> > 
> > I am really not sure how that works, the `install.sh` script handles virtual environments in our project, and it will always be located in `.venv`.
> > In any case, you need a separate one, as the instructions say.
> 
> I had created a virtual env denv in the begining where I installed everything in ycms. I followed the instructions also and added venv inside patient-to-room directory. and then I went back to ycms and ran it. clicking on suggest assignment didn't do anything for me. Am I supposed to directly click on that or I check in timetravel for assignments and then it will show

Alright, what's the console output when you click the button? And no, should not matter which one.

**Comment by charludo** [comment]
Actually, could you please also provide the output of `pwd` and `ls -al` from inside the solver directory?

A more direct way for trouble shooting could also be using `./tools/ycms-cli call_solver_api 1`, since this is what the ward/timeline views call

**Comment by SnehaR26** [comment]
> Actually, could you please also provide the output of `pwd` and `ls -al` from inside the solver directory?
> 
> A more direct way for trouble shooting could also be using `./tools/ycms-cli call_solver_api 1`, since this is what the ward/timeline views call

So when I click on the button I get the following output:

image

Console shows this :

image

So the main directory is hosproj under in which both ycms and pra reside.

image

**Comment by charludo** [comment]
> > Actually, could you please also provide the output of `pwd` and `ls -al` from inside the solver directory?
> > A more direct way for trouble shooting could also be using `./tools/ycms-cli call_solver_api 1`, since this is what the ward/timeline views call
> 
> So when I click on the button I get the following output:
> 
> image
> 
> Console shows this :
> 
> image
> 
> So the main directory is hosproj under in which both ycms and pra reside.
> 
> image

From the console error output: looks like you need a (free) license. Interesting. I got one but thought it's activation failed, but apparently not!

Have a look online, the license is pretty easy to get.

**Comment by SnehaR26** [comment]
Works for me👌👌. I can see suggested assignments for unassigned patients in the timeline view for past current and future. 
Do you want to wait till the final data before merging this?

**Comment by charludo** [comment]
> Works for me👌👌. I can see suggested assignments for unassigned patients in the timeline view for past current and future. Do you want to wait till the final data before merging this?

Great! And no, let's merge if you've no change requests.

**Review by SnehaR26 — APPROVED** [review]

**Pull request merged**
