### PR TITLE
Allow anonnymous patients

### LINKED ISSUE #98: Allow patients with no patient data
### Motivation

Emergency patients: don't care about data, just admit them and add data later

### Proposed Solution

Add third option in patient intake. 

Maybe also add "auto-assign bed immediately" checkbox? If the stay starts now.

### PR DESCRIPTION
**Pull request by charludo**
### Short description

This adds the option Mr. Mühlenbruch requested: Adding "unknown" patients. I've decided to require the approximate age and the gender of the patient for this, since these are required for a proper bed assignment and also known even when the patient is unconscious.

### Proposed changes

- 
- 

### Side effects

- 
- 

### Resolved issues

Fixes: #98

### CODE REVIEW

**Comment by SnehaR26** [comment]
Hi, it works as intended. I had a few suggestions:
- instead of approx age being a slider, can we make it in a range. 10-15, 15-20 or any custom value.
- It automatically assigns a discharge date in 7 weeks, do we need to have that field in the patient card?
- Not directly related to this but first we add the Unbekannt Unbekannt using Patient intake, then we go into ward view and manually assign the patient a bed. A feedback that Frau Büsing gave was that she expected the Manage Patients to perform the bed assignment/ discharge since the name says "manage patients". I know we do all this at a ward level, so should we think of some other name here to avoid this confusion?

**Comment by charludo** [comment]
> - instead of approx age being a slider, can we make it in a range. 10-15, 15-20 or any custom value.

Yeah, I though about this too, but was unsure how to set the ranges. If we do 5 years per category, that's 20 categories for 0-100, if we do fewer, it becomes trickier to decide what to choose. Could a slider that only does increments of 5 work?

> - It automatically assigns a discharge date in 7 weeks, do we need to have that field in the patient card?

We do need the discharge date, yes. The 7 days are basically random. We can put anything else, I am open to suggestions. Realistlcally, we would want the date to be set based on the diagnosis - but I have not been able to find data for that online. If we do, that would be great though!

> - Not directly related to this but first we add the Unbekannt Unbekannt using Patient intake, then we go into ward view and manually assign the patient a bed. A feedback that Frau Büsing gave was that she expected the Manage Patients to perform the bed assignment/ discharge since the name says "manage patients". I know we do all this at a ward level, so should we think of some other name here to avoid this confusion?

Yep, I'll add options related to that in #70. That should solve a lot of the issues we faced in the roleplay (for example cancelling patients that have not yet arrived at the hospital)

**Comment by charludo** [comment]
> * Not directly related to this but first we add the Unbekannt Unbekannt using Patient intake, then we go into ward view and manually assign the patient a bed. A feedback that Frau Büsing gave was that she expected the Manage Patients to perform the bed assignment/ discharge since the name says "manage patients". I know we do all this at a ward level, so should we think of some other name here to avoid this confusion?

Alright, this is partially fixed with #103, I think, but you are right, we could also rename the menu item to make it clearer - How about "Manage patient data" or even just "patient data"?

**Comment by charludo** [comment]
> > - It automatically assigns a discharge date in 7 weeks, do we need to have that field in the patient card?
> 
> We do need the discharge date, yes. The 7 days are basically random. We can put anything else, I am open to suggestions. Realistlcally, we would want the date to be set based on the diagnosis - but I have not been able to find data for that online. If we do, that would be great though!

Ohh I think I misunderstood, do you mean the roleplay cards Tabea gives us?

If so, yes, there is usually a planned discharge date, if I remember correctly

**Comment by charludo** [comment]
@SnehaR26 I've renamed the menu item and changed the slider step size. Would you be OK reviewing this one?

**Comment by SnehaR26** [comment]
> @SnehaR26 I've renamed the menu item and changed the slider step size. Would you be OK reviewing this one?

Hi @charludo All looks good 👍 . The 'Patient Data' is an apt name and the slider is also more functional now. Just one teeny tiny thing, If as a user I have accidentally pressed the gender option in the emergency intake, I can't undo it. My only option is to reload the page (since new patient fields are disabled). If this can be corrected by a small fix then maybe we try that if not then reload is also not much of a hassle.

**Comment by charludo** [comment]
> Hi @charludo All looks good 👍 . The 'Patient Data' is an apt name and the slider is also more functional now. Just one teeny tiny thing, If as a user I have accidentally pressed the gender option in the emergency intake, I can't undo it. My only option is to reload the page (since new patient fields are disabled). If this can be corrected by a small fix then maybe we try that if not then reload is also not much of a hassle.

Fair point! I've added reset buttons. 

(PS: if you go to "files changes" at the top of this PR, you can request chages, comment on specific lines, or approve from there!)

**Comment by SnehaR26** [comment]
Looks perfect now!👌

Next time I will make use of the file changes to comment. Thank you 😊

**Review by SnehaR26 — APPROVED** [review]

**Pull request merged**
